# For usage instructions see /config/sara/README.md
'USA':
  symptoms:
    'Fever':
      value: true
      type: 'BoolSymptom'
      notes: 'Feeling feverish or have a measured temperature at or above 100.4°F/38°C'
      required: true
      threshold_operator: 'Equal'
      group: 1
    'Used A Fever Reducer':
      value: true
      type: 'BoolSymptom'
      notes: 'In the past 24 hours, have you used any medicine that reduces fevers?'
      required: false
      threshold_operator: 'Equal'
      group: 2
    'Headache':
      value: true
      type: 'BoolSymptom'
      required: true
      threshold_operator: 'Equal'
      group: 1
    'Loss of Appetite':
      value: true
      type: 'BoolSymptom'
      required: true
      threshold_operator: 'Equal'
      group: 1
    'Muscle or Joint Pain':
      value: true
      type: 'BoolSymptom'
      required: true
      threshold_operator: 'Equal'
      group: 1
    'Fatigue':
      value: true
      type: 'BoolSymptom'
      notes: 'Feeling very tired or weak'
      required: true
      threshold_operator: 'Equal'
      group: 1
    'Rash':
      value: true
      type: 'BoolSymptom'
      required: true
      threshold_operator: 'Equal'
      group: 1
    'Vomiting':
      value: true
      type: 'BoolSymptom'
      required: true
      threshold_operator: 'Equal'
      group: 1
    'Diarrhea':
      value: true
      type: 'BoolSymptom'
      required: true
      threshold_operator: 'Equal'
      group: 1
    'Abdominal (Stomach) Pain':
      value: true
      type: 'BoolSymptom'
      required: true
      threshold_operator: 'Equal'
      group: 1
    'Bleeding Not Related to Injury':
      value: true
      type: 'BoolSymptom'
      required: true
      threshold_operator: 'Equal'
      group: 1
  children:
    'State 1':
      children:
        'County 1':
        'County 2':
    'State 2':
      children:
        'County 3':
        'County 4':
